#!/usr/bin/ruby
# coding: utf-8
#
# RICHO THETA S を操作する
#
# APIリファレンス:
#   https://developers.theta360.com/ja/docs/v2/api_reference/
#

require 'net/http'
require 'json'

class Theta
  def usage
    STDERR.puts <<EOF
theta: RICHO ThetaSのファイル操作など

Usage:
  % theta ls            # THETAの画像/動画ファイルをリストする
  % theta get uri       # THETAファイルをパソコンにコピーする
  % theta delete uri    # THETAファイルを削除する
  % theta volume        # シャッター音量を知る
  % theta volume val    # シャッター音量を設定する
EOF
    close if @sessionId
    exit
  end
  
  def exec(name, param)
    res = @http.post '/osc/commands/execute', {name:name, parameters:param}.to_json
    JSON.parse res.body
  end
  
  def initialize(args)
    @args = args
    usage if args.length == 0
    @http = Net::HTTP.new('192.168.1.1', 80)
    begin
      res = exec "camera.startSession", nil
      @sessionId = res["results"]["sessionId"]
    rescue
      puts "THETAが見つかりません。THETAのWiFiをONにしてパソコンからWiFi接続して下さい。"
      exit
    end

    cmd = args[0]
    if Theta.method_defined?(cmd.to_sym) then
      method(cmd.to_sym).call
      close
    else
      puts "コマンド '#{cmd}' は存在しません。"
      usage
    end
  end

  def close
    params = {sessionId: @sessionId}
    exec 'camera.closeSession', params
  end
  
  def ls
    token = nil
    while true do
      # res = exec "camera.listImages", { entryCount:10, includeThumb: false, continuationToken:token}
      res = exec "camera._listAll", { entryCount:10, includeThumb: false, continuationToken:token}
      token = res['results']['continuationToken']
      res['results']['entries'].each { |result|
        puts result
      }
      break unless token
    end
  end

  def get
    uri = @args[1]
    usage unless uri
    uri =~ /^(.*)\/(.*)$/
    name = $2
    if name =~ /JPG$/ then
      res = exec "camera.getImage", {fileUri: uri}
    elsif name =~ /MP4$/ then
      res = exec "camera._getVideo", {fileUri: uri}
    end
    open(name, "wb") {|f| f.write(res.body)}
  end

  def delete
    uri = @args[1]
    usage unless uri
    res = exec "camera.delete", {fileUri: uri}
  end

  def volume
    val = @args[1]
    if val then
      res = exec 'camera.setOptions', {sessionId: @sessionId, options:{_shutterVolume:val.to_i}}
      if res['state'] == "done"
        STDERR.puts "Thetaのシャッター音を #{val} に設定しました"
      else
        STDERR.puts "Thetaのシャッター音設定に失敗しました"
      end
    else
      res = exec 'camera.getOptions', {sessionId: @sessionId, optionNames:["_shutterVolume"]}
      STDERR.puts "Thetaのシャッター音量は #{res['results']['options']['_shutterVolume']} です"
    end
  end
end

theta = Theta.new ARGV
